# Generated by Django 3.2.6 on 2021-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subject_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=50)),
                ('subjects', models.ManyToManyField(to='core.Subject')),
            ],
        ),
    ]
